services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - microservice-net
    volumes:
      - ACIT3855-storage:/data
  kafka: 
    image: wurstmeister/kafka
    command: ["/bin/bash", "/reset_cluster.sh"]
    networks:
      - microservice-net
    environment:
      KAFKA_CREATE_TOPICS: "events:1:1" 
      KAFKA_ADVERTISED_HOST_NAME: localhost 
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ${KAFKA_DATA}:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/reset_cluster.sh:/reset_cluster.sh
    depends_on:
      - zookeeper
  receiver:
    build: 
      context: receiver
      dockerfile: Dockerfile
    restart: always
    # ports:
    #   - "8080:8080"
    volumes:
      - ${RECEIVER_CONF}:/app/config
      - ${RECEIVER_LOGS}:/app/logs

    depends_on:
      - kafka
    networks:
      - microservice-net
  storage:
    build: 
      context: storage
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ${STORAGE_CONF}:/app/config
      - ${STORAGE_LOGS}:/app/logs
    depends_on:
      - kafka
      - db
    networks:
      - microservice-net
  processing:
    build:
      context: processing
      dockerfile: Dockerfile
    environment:
      CORS_ALLOW_ALL: no
    # ports:
    #  - "8100:8100"
    volumes:
      - ${PROCESSING_CONF}:/app/config
      - ${PROCESSING_LOGS}:/app/logs
      - ${PROCESSING_DATA}:/app/stats
    depends_on:
      - storage
      - receiver
    networks:
      - microservice-net
  analyzer:
    build:
      context: analyzer
      dockerfile: Dockerfile
    environment:
      CORS_ALLOW_ALL: no
    volumes:
      - ${ANALYZER_CONF}:/app/config
      - ${ANALYZER_LOGS}:/app/logs
    # ports:
    #  - "8200:8200"
    depends_on:
      - receiver
      - storage
    networks:
      - microservice-net
  consistency_check:
    build: 
      context: consistency_check
      dockerfile: Dockerfile
    environment:
      CORS_ALLOW_ALL: no
    volumes:
       - ${CONSISTENCY_CONF}:/app/config
       - ${CONSISTENCY_LOGS}:/app/logs
       - ${CONSISTENCY_STATS}:/app/stats
    # ports:
    #  - "8400:8400"
    depends_on:
      - receiver
      - storage
      - analyzer
      - db
      - zookeeper
      - kafka
    networks:
      - microservice-net
  db:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: dev1
      MYSQL_PASSWORD: Dev1-mysql
      MYSQL_DATABASE: port-data
    networks:
      - microservice-net
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql
  dashboard:
    build:
      context: dashboard
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - receiver
      - storage
      - analyzer
      - processing
      - db
      - kafka
    networks:
      - microservice-net
networks:
  microservice-net:
    driver: bridge

volumes:
  ACIT3855-storage:
