version: 1
endpoints:
  processing_stats: 
    url: /processing/stats
  analyzer_stats:
    ship_url: /analyzer/ship_event_ids
    container_url : /analyzer/container_event_ids
  storage_stats:
    ship_url: /storage/ship_event_ids
    container_url : /storage/container_event_ids
datafile:
  path: /app/stats/consistency_stats.json
  file: consistency_stats.json

# curl -X POST http://consistency_check:8400/update
# curl  http://storage:8090/ship_event_ids
# curl  http://storage:8090/container_event_ids
# curl http://analyzer:8200/ship_event_ids
# curl http://analyzer:8200/container_event_ids