openapi: 3.0.0
info:
  title: Port
  description: Port event tracking
  version: 1.0.0.0
servers:
  - url: /
paths:
  /ship_arrival:
    get:
      tags:
        - ships
      summary: Returns ship event in the Kafka queue
      operationId: app.get_ship_event
      description: Returns the ship event located at index NUMBER in the Kafka queue
      parameters:
        - name: index
          in: query
          description: Event index to pull
          schema:
            type: number
            format: integer
            example: 5
      responses:
        "200":
          description: Successfully returned requeted event
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/Ship_Arrival"
        "404":
          description: No event found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /container_processing:
    get:
      tags:
        - containers
      summary: Returns container event in the Kafka queue
      operationId: app.get_container_event
      description: Returns the container event located at index NUMBER in the Kafka queue
      parameters:
        - name: index
          in: query
          description: Event index to pull
          schema:
            type: number
            format: integer
            example: 5
      responses:
        "200":
          description: Successfully returned requeted event
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/Container_Processing"
        "404":
          description: No event found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /stats:
    get:
      summary: Get stats about events
      operationId: app.get_stats
      description: Get stats about events
      responses:
        "200":
          description: Successfully returned stats
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/Stats"

components:
  schemas:
    Ship_Arrival:
      required:
        - ship_id
        - port_id
        - containers_onboard
        - docking_time
        - origin_country
      title: Ship_Arrival
      type: object
      properties:
        id:
          type: number
        ship_id:
          type: number
        port_id:
          type: number
          x-stoplight:
            id: 7o2upxybyi8af
        containers_onboard:
          type: number
          x-stoplight:
            id: tqb3u54ijnr18
        docking_time:
          type: string
          format: date-time
          x-stoplight:
            id: 4vx9e78s0qgvm
        origin_country:
          type: string
          x-stoplight:
            id: hwkbaf3smjas7
      description: ""
    Container_Processing:
      required:
        - container_id
        - processing_hub_id
        - container_weight
        - destination
        - unloading_time
      title: Container_Processing
      type: object
      properties:
        id:
          type: number
        container_id:
          type: number
        processing_hub_id:
          type: number
          x-stoplight:
            id: nhbyjvmuueuz7
        container_weight:
          type: number
          x-stoplight:
            id: zgepuhdzuh05g
        destination:
          type: string
          x-stoplight:
            id: f15qb11kgqqof
        unloading_time:
          type: string
          format: date-time
          x-stoplight:
            id: wo510kxf9qn30
    Stats:
      required:
        - num_ship_events
        - num_container_events
