version: 1
events:
  ship_arrivals:
    url: http://storage:8090/storage/ship/arrival
  container_processing:
    url: http://storage:8090/storage/container/arrival
  hostname: kafka
  port: 29092
  topic: events
