version: 1
datastore:
  filename: /app/stats/stats.json
scheduler:
  interval: 5
eventstores:
  ship_arrivals:
    url: /storage/ship/arrival
  container_processing:
    url: /storage/container/arrival
